name: mugsinc
favicon: null
layout_spectrum: 0.74677
typography_spectrum: 0.6414
title: mugsinc
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62532594-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.003135503036901355
  saturation: 0.315559706883505
  rhythmicContrast: 0.07814464950934052
purpose: []
